language: generic
sudo: required
services:
                - docker

before_install:
                - docker build -t akansha21/docker-react1 -f Dockerfile.dev .

script:
                - docker run -e CI=true akansha21/docker-react1 npm run test

